/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.List;
import modelo.Foro;
import modelo.Materia;
import modelo.Usuario;
import controlador.Controlador;
import dao.Persistencia;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Pregunta;

/**
 *
 * @author Usuario
 */
public class Buscar extends javax.swing.JFrame {

    Controlador controlador;
    JFrame previo;
    Usuario usuario;

    /**
     * Creates new form Buscar
     */
    public Buscar(JFrame p, Persistencia persi, Usuario user) {
        initComponents();
        controlador = new Controlador(persi);
        previo = p;
        usuario = user;
        cargarTodo();
        goButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        filter = new javax.swing.JButton();
        goButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(102, 0, 102));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Buscar:");

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(102, 0, 153));
        search.setText("");
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(102, 0, 153));
        backButton.setText("");
        backButton.setToolTipText("Haz click para Volver");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODO", "FOROS", "USUARIOS", "PREGUNTAS" }));

        filter.setBackground(new java.awt.Color(255, 255, 255));
        filter.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        filter.setForeground(new java.awt.Color(102, 0, 153));
        filter.setText("Aplicar Filtro");
        filter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        goButton.setBackground(new java.awt.Color(255, 255, 255));
        goButton.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        goButton.setForeground(new java.awt.Color(102, 0, 153));
        goButton.setText("Ir");
        goButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if (combo.getSelectedItem().toString() == "USUARIOS") {
            buscarUsuario();
        } else if (combo.getSelectedItem().toString() == "FOROS") {
            buscarForo();
        } else if (combo.getSelectedItem().toString() == "PREGUNTAS") {
            buscarPregunta();
        } else if (combo.getSelectedItem().toString() == "TODO") {
            buscarTodo();
        }
    }//GEN-LAST:event_searchActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        if (combo.getSelectedItem().toString() == "USUARIOS") {
            cargarUsuario();
        } else if (combo.getSelectedItem().toString() == "FOROS") {
            cargarForo();
        } else if (combo.getSelectedItem().toString() == "PREGUNTAS") {
            cargarPregunta();
        } else if (combo.getSelectedItem().toString() == "TODO") {
            cargarTodo();
        }
    }//GEN-LAST:event_filterActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (this.jTextField1.getText().length() >= 2) {
            if (combo.getSelectedItem().toString() == "USUARIOS") {
                buscarUsuario();
            } else if (combo.getSelectedItem().toString() == "FOROS") {
                buscarForo();
            } else if (combo.getSelectedItem().toString() == "PREGUNTAS") {
                buscarPregunta();
            } else if (combo.getSelectedItem().toString() == "TODO") {
                buscarTodo();
            }
        }
        if (this.jTextField1.getText().length() < 2) {
            if (combo.getSelectedItem().toString() == "USUARIOS") {
                cargarUsuario();
            } else if (combo.getSelectedItem().toString() == "FOROS") {
                cargarForo();
            } else if (combo.getSelectedItem().toString() == "PREGUNTAS") {
                cargarPregunta();
            } else if (combo.getSelectedItem().toString() == "TODO") {
                cargarTodo();
            }
        }

    }//GEN-LAST:event_jTextField1KeyTyped

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        goButton.setEnabled(true);
    }//GEN-LAST:event_jList1ValueChanged

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        try {
            Usuario seleccionado = (Usuario) this.jList1.getSelectedValue();
            VerPerfil vista = new VerPerfil(this, this.controlador.getPersistencia(), (Usuario) this.jList1.getSelectedValue(), 1);
            if (this.usuario.getId().equals(seleccionado.getId())) {
                vista = new VerPerfil(this, this.controlador.getPersistencia(), (Usuario) this.jList1.getSelectedValue(), 0);
            }
            vista.setVisible(true);
          
            vista.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            //error handling code
        }

        try {
            Pregunta _preg = (Pregunta) this.jList1.getSelectedValue();
            ViewPregunta vista = new ViewPregunta(this, (Pregunta) this.jList1.getSelectedValue(), _preg.getForo(), this.controlador, this.usuario);
          
            vista.setLocationRelativeTo(null);
            vista.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            //error handling code
        }

        try {
            ViewForo foro = new ViewForo(this, (Foro) this.jList1.getSelectedValue(), this.controlador, this.usuario);
            foro.setVisible(true);
           
            foro.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            //error handling code
        }


    }//GEN-LAST:event_goButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void cargarTodo() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.listarForos().forEach((forito) -> {
            modelo.addElement(forito);
        });
        this.controlador.listarUsuarios().forEach((user) -> {
            modelo.addElement(user);
        });
        this.controlador.listarPregunta().forEach((preg) -> {
            modelo.addElement(preg);
        });
        this.jList1.setModel(modelo);
    }

    private void cargarForo() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.listarForos().forEach((forito) -> {
            modelo.addElement(forito);
        });
        this.jList1.setModel(modelo);
    }

    private void cargarUsuario() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.listarUsuarios().forEach((user) -> {

            modelo.addElement(user);
        });
        this.jList1.setModel(modelo);
    }

    private void cargarPregunta() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.listarPregunta().forEach((preg) -> {
            modelo.addElement(preg);
        });
        this.jList1.setModel(modelo);
    }

    private void buscarTodo() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.buscarForos(this.jTextField1.getText()).forEach((forito) -> {
            modelo.addElement(forito);
        });
        this.controlador.buscarUsuarios(this.jTextField1.getText()).forEach((user) -> {
            modelo.addElement(user);
        });
        this.controlador.buscarPreguntas(this.jTextField1.getText()).forEach((preg) -> {
            modelo.addElement(preg);
        });
        this.jList1.setModel(modelo);
    }

    private void buscarForo() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.buscarForos(this.jTextField1.getText()).forEach((forito) -> {
            modelo.addElement(forito);
        });
        this.jList1.setModel(modelo);
    }

    private void buscarUsuario() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.buscarUsuarios(this.jTextField1.getText()).forEach((user) -> {
            modelo.addElement(user);
        });
        this.jList1.setModel(modelo);
    }

    private void buscarPregunta() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.buscarPreguntas(this.jTextField1.getText()).forEach((preg) -> {
            modelo.addElement(preg);
        });
        this.jList1.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton filter;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Object> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
