/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Controlador;
import dao.Persistencia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import modelo.Foro;
import modelo.Materia;

import modelo.Usuario;
import servicios.Hash;

/**
 *
 * @author malve
 */
public final class MainFrame extends javax.swing.JFrame {

    Controlador controlador;
    JFrame previo;
    Usuario usuario;
    Materia materia1;

    public MainFrame(Persistencia persi, Usuario usu) {
        controlador = new Controlador(persi);
        usuario = usu;
        this.previo = previo;
        initComponents();
        this.cargarComboBoxUsuario();
        this.limpiarCrearUsuario();
        this.cargarForo();
        List<String> datosUsuario = this.controlador.obtenerDatosUsuario(this.usuario);
        this.labelUsuario.setText(datosUsuario.get(0) + ' ' + datosUsuario.get(1));
        this.labelTipoUsuario.setText(datosUsuario.get(4));
        this.buttonRealizarCambios.setEnabled(false);
        switch (datosUsuario.get(4)) {
            case Usuario.ESTUDIANTE:
                this.jButton9.setVisible(false);
                this.jButton2.setVisible(false);

                this.jTabbedPane1.setEnabledAt(1, false);
                this.jTabbedPane1.setEnabledAt(2, false);
                this.jTabbedPane1.setEnabledAt(3, false);
                break;
            case Usuario.PROFESOR:
                this.jButton9.setVisible(false);
                this.jButton2.setVisible(false);

                this.jTabbedPane1.setEnabledAt(1, false);
                this.jTabbedPane1.setEnabledAt(2, false);
                this.jTabbedPane1.setEnabledAt(3, false);
                break;
            case Usuario.REGISTRADOR:
                this.jButton9.setVisible(false);
                this.jButton2.setVisible(false);
                this.searchButton.setEnabled(false);
                // this.jMenuItem1.setEnabled(false);
                this.jTabbedPane1.setEnabledAt(1, false);
                this.jTabbedPane1.setEnabledAt(2, false);
                this.jTabbedPane1.setEnabledAt(0, false);
                this.jTabbedPane1.setSelectedIndex(3);
                break;
            default:
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelTipoUsuario = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListForos = new javax.swing.JList<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        textUsuarioFiltro = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        comboBoxUsuariosFiltro = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        textMateria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaMateria = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMaterias = new javax.swing.JList<>();
        buttonCrear = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonRealizarCambios = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        buttonQuitarMateria = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxUsuario = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        textNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textDocumento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        closeSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        searchButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BitNet");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(153, 0, 153));
        labelUsuario.setText("NameAndSurName");

        labelTipoUsuario.setText("Rol");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 0));
        jButton2.setText("");
        jButton2.setToolTipText("Haz click para crear un nuevo Foro");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ListForos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ListForos.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        ListForos.setForeground(new java.awt.Color(102, 0, 102));
        ListForos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListForos.setSelectionBackground(new java.awt.Color(153, 153, 153));
        ListForos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListForosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListForos);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 0, 0));
        jButton9.setText("");
        jButton9.setToolTipText("Haz click para borrar un Foro");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(102, 0, 153));
        jButton10.setText("Entrar al Foro");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logobitnet.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(868, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(151, 151, 151))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTipoUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Foros", jPanel1);

        listUsers.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        listUsers.setForeground(new java.awt.Color(102, 0, 102));
        listUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listUsers.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(listUsers);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setText("");
        jButton6.setToolTipText("Haz click para modificar un usuario");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        textUsuarioFiltro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textUsuarioFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textUsuarioFiltroKeyTyped(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 0, 153));
        jButton7.setText("");
        jButton7.setToolTipText("Haz click para buscar un usuario");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        comboBoxUsuariosFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ADMINISTRADOR", "PROFESOR", "ESTUDIANTE", "REGISTRADOR", "CORREO", "DOCUMENTO" }));
        comboBoxUsuariosFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxUsuariosFiltroItemStateChanged(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(204, 0, 0));
        jButton11.setText("");
        jButton11.setToolTipText("Haz click para eliminar un usuario");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboBoxUsuariosFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textUsuarioFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxUsuariosFiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(textUsuarioFiltro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Todos los usuarios", jPanel3);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });

        jLabel1.setText("Materia:");

        jLabel2.setText("Enlace:");

        textAreaMateria.setColumns(20);
        textAreaMateria.setRows(5);
        jScrollPane3.setViewportView(textAreaMateria);

        listMaterias.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        listMaterias.setForeground(new java.awt.Color(102, 0, 102));
        listMaterias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listMaterias.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane4.setViewportView(listMaterias);

        buttonCrear.setBackground(new java.awt.Color(255, 255, 255));
        buttonCrear.setForeground(new java.awt.Color(102, 0, 153));
        buttonCrear.setText("Crear");
        buttonCrear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        buttonModificar.setBackground(new java.awt.Color(255, 255, 255));
        buttonModificar.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        buttonModificar.setForeground(new java.awt.Color(0, 0, 204));
        buttonModificar.setText("");
        buttonModificar.setToolTipText("Haz click para modificar una materia");
        buttonModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonRealizarCambios.setBackground(new java.awt.Color(255, 255, 255));
        buttonRealizarCambios.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        buttonRealizarCambios.setForeground(new java.awt.Color(102, 0, 153));
        buttonRealizarCambios.setText("Realizar cambio");
        buttonRealizarCambios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        buttonRealizarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRealizarCambiosActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 0, 153));
        jButton8.setText("Cancelar cambio");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        buttonQuitarMateria.setBackground(new java.awt.Color(255, 255, 255));
        buttonQuitarMateria.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        buttonQuitarMateria.setForeground(new java.awt.Color(204, 0, 0));
        buttonQuitarMateria.setText("");
        buttonQuitarMateria.setToolTipText("Haz click para eliminar una materia");
        buttonQuitarMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        buttonQuitarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(buttonQuitarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(buttonRealizarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(94, 94, 94)
                            .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3)
                        .addComponent(textMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRealizarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonQuitarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Materias", jPanel4);

        jLabel3.setText("Apellido:");

        jLabel4.setText("Email:");

        comboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Documento:");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe MDL2 Assets", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 0));
        jButton4.setText("");
        jButton4.setToolTipText("Haz click para crear el usuario");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de usuario:");

        textDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDocumentoKeyTyped(evt);
            }
        });

        jLabel8.setText("Nombre:");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe MDL2 Assets", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 0, 0));
        jButton5.setText("");
        jButton5.setToolTipText("Haz click para cancelar");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxUsuario, 0, 209, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textApellido)
                            .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))))
                .addGap(331, 331, 331))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nuevo usuario", jPanel2);

        jMenu1.setText("Cuenta");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Ver Perfil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        closeSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        closeSesion.setText("Cerrar Sesion");
        closeSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSesionActionPerformed(evt);
            }
        });
        jMenu1.add(closeSesion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Más");

        searchButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jMenu2.add(searchButton);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.cargarForo();
        this.cargarMaterias();
        this.jButton10.setEnabled(false);
        this.jButton9.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // if ((this.controlador.verPerfilEstudiante(usuario) != null) || (this.controlador.verPerfilProfesor(usuario) != null)) {
        VerPerfil vista = new VerPerfil(this, this.controlador.getPersistencia(), this.usuario, 0);
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
        //}

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void closeSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSesionActionPerformed
        this.dispose();

        StartSesion sesion = new StartSesion();
        sesion.limpiar();
        sesion.setVisible(true);
        sesion.setLocationRelativeTo(null);

    }//GEN-LAST:event_closeSesionActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        this.cargarForo();
        this.cargarUsuarios(this.comboBoxUsuariosFiltro.getSelectedItem().toString(), this.textUsuarioFiltro.getText());
        if (this.comboBoxUsuariosFiltro.getSelectedItem().toString() == "TODOS") {
            textUsuarioFiltro.setEnabled(false);
            textUsuarioFiltro.setText("");
            this.jButton7.setEnabled(false);
        } else {
            textUsuarioFiltro.setEnabled(true);
            this.jButton7.setEnabled(true);
        }
        this.cargarMaterias();
        this.jButton10.setEnabled(false);
        this.jButton9.setEnabled(false);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.limpiarCrearUsuario();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void textDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDocumentoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_textDocumentoKeyTyped

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify                     

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (textEmail.getText().contains("@") && textEmail.getText().contains(".")) {
            this.aceptar();
        } else {
            JOptionPane.showMessageDialog(null, "Correo ingresado sin '@' y/o '.'! ", "Error en campo Correo", JOptionPane.ERROR_MESSAGE);
            textEmail.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered

    }//GEN-LAST:event_jPanel4MouseEntered

    private void buttonQuitarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitarMateriaActionPerformed
        if (this.listMaterias.getSelectedIndex() != -1) {
            this.controlador.eliminarMateria(this.listMaterias.getSelectedValue());
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna materia");
        }
    }//GEN-LAST:event_buttonQuitarMateriaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.textMateria.setText("");
        this.textAreaMateria.setText("");
        this.buttonRealizarCambios.setEnabled(false);
        this.buttonCrear.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void buttonRealizarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRealizarCambiosActionPerformed
        if (this.textMateria.getText().equals("") || this.textAreaMateria.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No cargo completamente los datos");

        } else if (this.controlador.modificarMateria(this.materia1, this.textMateria.getText(), this.textAreaMateria.getText())) {
            this.cargarMaterias();
            this.textMateria.setText("");
            this.textAreaMateria.setText("");
            this.buttonRealizarCambios.setEnabled(false);
            this.buttonCrear.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha creado la materia");
        }
    }//GEN-LAST:event_buttonRealizarCambiosActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        if (this.listMaterias.getSelectedIndex() != -1) {
            this.textMateria.setText(this.listMaterias.getSelectedValue().getMateria());
            this.textAreaMateria.setText(this.listMaterias.getSelectedValue().getEnlace());
            this.materia1 = this.listMaterias.getSelectedValue();
            this.buttonRealizarCambios.setEnabled(true);
            this.buttonCrear.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "No selecciono ninguna materia");
        }
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        if (this.textMateria.getText().equals("") || this.textAreaMateria.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No cargo completamente los datos");

        } else if (this.controlador.crearMateria(this.textMateria.getText(), this.textAreaMateria.getText())) {
            this.cargarMaterias();
            this.textMateria.setText("");
            this.textAreaMateria.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se ha creado la materia");
        }
    }//GEN-LAST:event_buttonCrearActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (this.listUsers.getSelectedIndex() != -1) {
            if (!this.controlador.eliminarUsuario(this.listUsers.getSelectedValue())) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar el administrador porque tiene asociado preguntas, respuestas o votos");
            }
            this.cargarUsuarios(this.comboBoxUsuariosFiltro.getSelectedItem().toString(), this.textUsuarioFiltro.getText());
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun usuario");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void comboBoxUsuariosFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxUsuariosFiltroItemStateChanged
        if (this.comboBoxUsuariosFiltro.getSelectedItem().toString() == "TODOS") {
            textUsuarioFiltro.setEnabled(false);
            this.jButton7.setEnabled(false);
            textUsuarioFiltro.setText("");
            this.cargarUsuarios(this.comboBoxUsuariosFiltro.getSelectedItem().toString(), this.textUsuarioFiltro.getText());
        } else {
            textUsuarioFiltro.setEnabled(true);
            this.jButton7.setEnabled(true);
        }
    }//GEN-LAST:event_comboBoxUsuariosFiltroItemStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (this.comboBoxUsuariosFiltro.getSelectedItem().toString() == "CORREO") {
            if (textUsuarioFiltro.getText().contains("@") && textUsuarioFiltro.getText().contains(".")) {
                this.cargarUsuarios(this.comboBoxUsuariosFiltro.getSelectedItem().toString(), this.textUsuarioFiltro.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Correo ingresado sin '@' y/o '.'! ", "Error en campo Buscar", JOptionPane.ERROR_MESSAGE);
                textUsuarioFiltro.setText("");
            }
        } else {
            this.cargarUsuarios(this.comboBoxUsuariosFiltro.getSelectedItem().toString(), this.textUsuarioFiltro.getText());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void textUsuarioFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUsuarioFiltroKeyTyped
        if (this.comboBoxUsuariosFiltro.getSelectedItem().toString() == "DOCUMENTO") {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_textUsuarioFiltroKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (this.listUsers.getSelectedIndex() != -1) {
            ModificarUsuario modificar = new ModificarUsuario(this, this.controlador, this.listUsers.getSelectedValue());
            modificar.setVisible(true);

            modificar.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        ViewForo foro = new ViewForo(this, this.ListForos.getSelectedValue(), this.controlador, this.usuario);
        foro.setVisible(true);

        foro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (this.ListForos.getSelectedIndex() != -1) {
            if (this.usuario.getTipoUsuario().equals(Usuario.ADMINISTRADOR)) {
                Boolean respuesta = false;

                VistaAvisoDialog aviso = new VistaAvisoDialog(this, true, respuesta, "Se eliminara todos las preguntas, respuestas y asociaciones");
                aviso.setVisible(true);

                respuesta = aviso.obtenerRespuesta();
                if (respuesta) {

                    this.controlador.eliminarForo(this.ListForos.getSelectedValue());
                    this.cargarForo();
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun foro");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CrearForo foro = new CrearForo(this, this.controlador.getPersistencia());
        foro.setVisible(true);

        foro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        Buscar vista = new Buscar(this, this.controlador.getPersistencia(), this.usuario);
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void ListForosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListForosValueChanged
        this.jButton10.setEnabled(true);
        this.jButton9.setEnabled(true);
    }//GEN-LAST:event_ListForosValueChanged

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    public void cargarComboBoxUsuario() {
        List<String> datosUsuario = this.controlador.obtenerDatosUsuario(this.usuario);
        ArrayList<String> a = new ArrayList<>();
        if ("REGISTRADOR".equals(datosUsuario.get(4).toUpperCase())) {
            a.add(Usuario.REGISTRADOR);
            a.add(Usuario.ESTUDIANTE);
            a.add(Usuario.PROFESOR);
        } else {
            a.add(Usuario.ADMINISTRADOR);
            a.add(Usuario.ESTUDIANTE);
            a.add(Usuario.REGISTRADOR);
            a.add(Usuario.PROFESOR);
        }

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(a.toArray());
        this.comboBoxUsuario.setModel(modelo);
    }

    public void aceptar() {
        if (!this.textApellido.getText().equals("")) {
            if (!this.textNombre.getText().equals("")) {
                if (!this.textDocumento.getText().equals("")) {
                    if (!this.textEmail.getText().equals("")) {
                        if (this.controlador.crearUsuario(this.textNombre.getText().toUpperCase(), this.textApellido.getText().toUpperCase(), this.textEmail.getText(), this.textDocumento.getText(), Hash.MD5("none"), this.comboBoxUsuario.getSelectedItem().toString().toUpperCase())) {
                            JOptionPane.showMessageDialog(null, "Se a creado correctamente el usuario");
                            this.limpiarCrearUsuario();
                        } else {

                            JOptionPane.showMessageDialog(null, "No se a creado  el usuario");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No ha completado el email");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No ha completado el documento");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No ha completado el nombre");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha completado el apellido");
        }
    }

    public void limpiarCrearUsuario() {
        this.textApellido.setText("");
        this.textNombre.setText("");
        this.textDocumento.setText("");
        this.textEmail.setText("");

    }

    public void cargarForo() {
        DefaultListModel modelo = new DefaultListModel();
        this.controlador.listarForos().forEach((forito) -> {
            modelo.addElement(forito);
        });
        this.ListForos.setModel(modelo);
    }

    public void cargarUsuarios(String filtro, String nombre) {

        DefaultListModel modelo = new DefaultListModel();
        List<Usuario> lista = this.controlador.listarUsuariosPersonalizado(filtro, nombre);
        for (Usuario user : lista) {
            modelo.addElement(user);
        }
        this.listUsers.setModel(modelo);
    }

    public void cargarMaterias() {

        DefaultListModel modelo = new DefaultListModel();
        for (Materia materia : this.controlador.listarMaterias()) {
            modelo.addElement(materia);
        }
        this.listMaterias.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Foro> ListForos;
    private javax.swing.JButton buttonCrear;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonQuitarMateria;
    private javax.swing.JButton buttonRealizarCambios;
    private javax.swing.JMenuItem closeSesion;
    private javax.swing.JComboBox<String> comboBoxUsuario;
    private javax.swing.JComboBox<String> comboBoxUsuariosFiltro;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelTipoUsuario;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JList<Materia> listMaterias;
    private javax.swing.JList<Usuario> listUsers;
    private javax.swing.JMenuItem searchButton;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextArea textAreaMateria;
    private javax.swing.JTextField textDocumento;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textMateria;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textUsuarioFiltro;
    // End of variables declaration//GEN-END:variables
}
