/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.glass.events.KeyEvent;
import modelo.UsuarioAcademico;
import controlador.Controlador;
import dao.Persistencia;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import modelo.Materia;
import modelo.Pregunta;

import modelo.Respuesta;
import modelo.Usuario;
import servicios.Hash;

/**
 *
 * @author Admin
 */
public class VerPerfil extends javax.swing.JFrame {
    
    private Controlador controlador;
    //private UsuarioAcademico profe, estu, admin;
    //private Usuario reg;
    private JFrame previo;
    private Usuario usuario;

    /**
     * Creates new form VerPerfil
     *
     * @param usuario
     *
     * @param p
     * @param usua
     * @param per
     */
    //si visualizacion es 0 quiere decir que el usuario ingreso a ver su perfil propio,
    //si visualziacion es 1 es porque otro usuario esta viendo este perfil por lo tanto hay que ocultar la opcino cambiar passsword
    public VerPerfil(JFrame p, Persistencia per, Usuario usua, Integer visualizacion) {
        controlador = new Controlador(per);
        previo = p;
        usuario = usua;
        initComponents();
        this.comboBoxMaterias.setVisible(false);
        this.jLabel7.setVisible(false);
        if (this.controlador.esUsuarioProfesor(usua)) {
            this.comboBoxMaterias.setVisible(true);
            this.jLabel7.setVisible(true);
        } else {
            if (this.controlador.esUsuarioAdministrador(usua)) {
                //this.jLabel4.setVisible(false);
                //this.textReputacion.setVisible(false);
            } else {
                if (this.controlador.esUsuarioRegistrador(usua)) {
                    /* this.jLabel4.setVisible(false);
                    this.textReputacion.setVisible(false);
                    this.jLabel5.setVisible(false);
                    this.textRespuestas.setVisible(false);
                    this.jLabel6.setVisible(false);
                    this.textPreguntas.setVisible(false);
                    this.jLabel8.setVisible(false);
                    this.listPreguntas.setVisible(false);
                    this.listPreguntas.setVisible(false);
                    jLabel5.setVisible(false);*/
                }
            }
        }
        this.cargarDatos();
        this.textReputacion.setEditable(false);
        this.textApellido.setEditable(false);
        this.textNombre.setEditable(false);
        this.textEmail.setEditable(false);
        this.textPreguntas.setEditable(false);
        this.textRespuestas.setEditable(false);
        this.jPasswordField1.setEditable(false);
        if (visualizacion == 1) {
            this.labelPassword.setVisible(false);
            this.jPasswordField1.setVisible(false);
            this.buttonModificar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxMaterias = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textReputacion = new javax.swing.JTextField();
        textPreguntas = new javax.swing.JTextField();
        textRespuestas = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        buttonModificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPreguntas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listRespuestas = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Perfil - BitNet");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Email:");

        jLabel4.setText("Reputacion:");

        jLabel5.setText("Respuestas realizadas:");

        jLabel6.setText("Pregutas :");

        jLabel7.setText("Materias asignadas:");

        comboBoxMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMateriasActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 153));
        jButton1.setText("");
        jButton1.setToolTipText("Haz click para Volver");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textNombre.setEditable(false);

        textApellido.setEditable(false);

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });

        textReputacion.setEditable(false);

        textPreguntas.setEditable(false);

        textRespuestas.setEditable(false);

        labelPassword.setText("Password:");

        jPasswordField1.setText("adminBitNet");

        buttonModificar.setBackground(new java.awt.Color(255, 255, 255));
        buttonModificar.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        buttonModificar.setForeground(new java.awt.Color(102, 0, 153));
        buttonModificar.setText("Cambiar contraseña");
        buttonModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        listPreguntas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPreguntasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPreguntas);

        listRespuestas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRespuestasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listRespuestas);

        jLabel8.setText("Respuestas :");

        jLabel9.setText("Pregutas realizadas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textApellido)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textReputacion, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textReputacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        if ("Modificar Password".equals(this.buttonModificar.getText())) {
            this.jPasswordField1.setEditable(true);
            this.buttonModificar.setText("Guardar");
            this.jPasswordField1.setText("");
        } else {
            this.jPasswordField1.setEditable(false);
            char[] arrayC = jPasswordField1.getPassword();
            String pass = new String(arrayC);
            String pass2 = Hash.MD5(pass);
            this.controlador.cambiarPassUsuario(usuario, pass2);
            this.buttonModificar.setText("Modificar Password");
        }

    }//GEN-LAST:event_buttonModificarActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void comboBoxMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMateriasActionPerformed
        if (this.comboBoxMaterias.getSelectedIndex() != -1) {
            
            Materia materia = (Materia) this.comboBoxMaterias.getSelectedItem();
            
            Desktop enlace = Desktop.getDesktop();
            try {
                enlace.browse(new URI(materia.getEnlace()));
            } catch (IOException | URISyntaxException e) {
                e.getMessage();
            }
        }
    }//GEN-LAST:event_comboBoxMateriasActionPerformed

    private void listPreguntasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPreguntasValueChanged
        if (this.listPreguntas.getSelectedIndex() != -1) {
            Pregunta pregunta = this.listPreguntas.getSelectedValue();
            ViewPregunta vistaPregunta = new ViewPregunta(this, pregunta, pregunta.getForo(), this.controlador, this.usuario);
            vistaPregunta.setVisible(true);
            vistaPregunta.setLocationRelativeTo(null);
            this.dispose();
        }

    }//GEN-LAST:event_listPreguntasValueChanged

    private void listRespuestasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRespuestasValueChanged
        if (this.listRespuestas.getSelectedIndex() != -1) {
            
            Respuesta respuesta = this.listRespuestas.getSelectedValue();
            ViewPregunta vistaPregunta = new ViewPregunta(this, respuesta.getPregunta(), respuesta.getPregunta().getForo(), this.controlador, this.usuario);
            vistaPregunta.setVisible(true);
            vistaPregunta.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_listRespuestasValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param datos
     */
    public void cargarComboBoxMateria(ArrayList datos) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(this.controlador.obtenerMateriasProfesor(this.usuario).toArray());
        this.comboBoxMaterias.setModel(modelo);
    }

   
    /* [0]=materias [1]=reputacion [2]=apellido [3]=nombre [4]=correo 
    [5]=cantidad de preguntas [6]=cantidad de respuestas*/
    public void cargarDatos() {
        ArrayList<Object> datos = (ArrayList<Object>) this.controlador.obtenerDatosVerPerfil(this.usuario);
        if (this.controlador.esUsuarioProfesor(usuario)) {
            cargarComboBoxMateria(datos);
        }
        this.textReputacion.setText(Integer.toString((int) datos.get(0)));
        this.textApellido.setText(datos.get(1).toString());
        this.textNombre.setText(datos.get(2).toString());
        this.textEmail.setText(datos.get(3).toString());
        this.jPasswordField1.setText("");
        if (!this.controlador.esUsuarioRegistrador(usuario)) {
            this.textPreguntas.setText(Integer.toString(((List<Pregunta>) datos.get(4)).size()));
            this.textRespuestas.setText(Integer.toString(((List<Respuesta>) datos.get(5)).size()));
            this.cargarListaPreguntas((List<Pregunta>) datos.get(4));
            this.cargarListaRespuestas((List<Respuesta>) datos.get(5));
        }
    }
    
    public void cargarListaPreguntas(List<Pregunta> preguntas) {
        List<Pregunta> lista = new ArrayList<Pregunta>();
        lista = preguntas;
        
        DefaultListModel model = new DefaultListModel();
        for (Pregunta unaPregunta : lista) {
            model.addElement(unaPregunta);
        }
        this.listPreguntas.setModel(model);
    }
    
    public void cargarListaRespuestas(List<Respuesta> respuestas) {
        List<Respuesta> lista = new ArrayList<Respuesta>();
        lista = respuestas;
        
        DefaultListModel model = new DefaultListModel();
        for (Respuesta unaRespuesta : lista) {
            model.addElement(unaRespuesta);
        }
        this.listRespuestas.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModificar;
    private javax.swing.JComboBox<Materia> comboBoxMaterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JList<Pregunta> listPreguntas;
    private javax.swing.JList<Respuesta> listRespuestas;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPreguntas;
    private javax.swing.JTextField textReputacion;
    private javax.swing.JTextField textRespuestas;
    // End of variables declaration//GEN-END:variables
}
