/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Controlador;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import modelo.Foro;
import modelo.Pregunta;
import modelo.Respuesta;
import modelo.Usuario;

/**
 *
 * @author Alexander
 */
public final class ViewForo extends javax.swing.JFrame {

    JFrame previo;
    Foro foro;
    Controlador controlador;
    Usuario usuario;

    /**
     * Creates new form Foro
     *
     * @param name
     * @param p
     * @param per
     * @param usu
     */
    public ViewForo(JFrame p, Foro name, Controlador c, Usuario usu) {
        previo = p;
        foro = name;
        usuario = usu;
        this.controlador = c;
        initComponents();
        this.buttonVerPregunta.setEnabled(false);
        String titulo = "FORO";
        try {
            titulo = name.getTitulo();
            this.nameForo.setText(titulo);
            this.cargarListPreguntas();
        } catch (Exception ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        nameForo = new javax.swing.JLabel();
        BtnAddAnswer = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPreguntas = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDetalle = new javax.swing.JList<>();
        buttonVerPregunta = new javax.swing.JButton();
        buttonVerPregunta1 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Preguntas - BitNet");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        nameForo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameForo.setForeground(new java.awt.Color(153, 0, 153));
        nameForo.setText("NameForo");

        BtnAddAnswer.setBackground(new java.awt.Color(255, 255, 255));
        BtnAddAnswer.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        BtnAddAnswer.setForeground(new java.awt.Color(102, 0, 153));
        BtnAddAnswer.setText("Publicar Pregunta");
        BtnAddAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        BtnAddAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddAnswerActionPerformed(evt);
            }
        });

        returnBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnBtn.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        returnBtn.setForeground(new java.awt.Color(102, 0, 153));
        returnBtn.setText("");
        returnBtn.setToolTipText("Haz click para Volver");
        returnBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        listPreguntas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        listPreguntas.setForeground(new java.awt.Color(102, 0, 102));
        listPreguntas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPreguntas.setSelectionBackground(new java.awt.Color(153, 153, 153));
        listPreguntas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPreguntasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listPreguntas);

        listDetalle.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        listDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDetalle.setSelectionBackground(new java.awt.Color(204, 204, 204));
        listDetalle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDetalleValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listDetalle);

        buttonVerPregunta.setBackground(new java.awt.Color(255, 255, 255));
        buttonVerPregunta.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        buttonVerPregunta.setForeground(new java.awt.Color(102, 0, 153));
        buttonVerPregunta.setText("Ver Pregunta");
        buttonVerPregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        buttonVerPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPreguntaActionPerformed(evt);
            }
        });

        buttonVerPregunta1.setBackground(new java.awt.Color(255, 255, 255));
        buttonVerPregunta1.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        buttonVerPregunta1.setForeground(new java.awt.Color(204, 0, 0));
        buttonVerPregunta1.setText("");
        buttonVerPregunta1.setToolTipText("Haz click para eliminar una Pregunta");
        buttonVerPregunta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        buttonVerPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPregunta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameForo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVerPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonVerPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameForo)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVerPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonVerPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// CON EL PREVIO DABA ERROR EN EL NOMBRE DEL FORO
    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed

        this.previo.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_returnBtnActionPerformed

    private void BtnAddAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddAnswerActionPerformed
        PublicarPregunta principal = new PublicarPregunta(this, this.foro, this.controlador, this.usuario);
        principal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_BtnAddAnswerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            this.cargarListPreguntas();
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_formWindowActivated

    private void listPreguntasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPreguntasValueChanged

        this.cargarListaDetalle();
        if (this.listPreguntas.getSelectedIndex() != -1) {
            this.buttonVerPregunta.setEnabled(true);
        } else {
            this.buttonVerPregunta.setEnabled(false);
        }

    }//GEN-LAST:event_listPreguntasValueChanged

    private void buttonVerPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerPreguntaActionPerformed
        if (this.listPreguntas.getSelectedIndex() != -1) {
            ViewPregunta vista = new ViewPregunta(this, this.listPreguntas.getSelectedValue(), this.foro, this.controlador, this.usuario);
            vista.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            vista.setLocationRelativeTo(null);
            vista.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_buttonVerPreguntaActionPerformed

    private void buttonVerPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerPregunta1ActionPerformed
        if (this.listPreguntas.getSelectedIndex() != -1) {
            if (this.controlador.esUsuarioAdministrador(usuario)) {
                Boolean respuesta = false;

                VistaAvisoDialog aviso = new VistaAvisoDialog(this, true, respuesta, "Se eliminara todos las respuestas y asociaciones");
                aviso.setVisible(true);

                respuesta = aviso.obtenerRespuesta();
                if (respuesta) {

                    this.controlador.eliminarPregunta(this.listPreguntas.getSelectedValue());
                    this.cargarListPreguntas();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna pregunta");
        }
    }//GEN-LAST:event_buttonVerPregunta1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void listDetalleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDetalleValueChanged
        if (this.listDetalle.getSelectedIndex() == 1) {
            if (this.listPreguntas.getSelectedValue() != null) {
                VerPerfil perfil = new VerPerfil(this, this.controlador.getPersistencia(), this.listPreguntas.getSelectedValue().getUsuario(), 1);
                perfil.setVisible(true);
                perfil.setLocationRelativeTo(null);
                perfil.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();

            }

        }
    }//GEN-LAST:event_listDetalleValueChanged

    public void cargarListPreguntas() {
        DefaultListModel modelo = new DefaultListModel();
        Arrays.sort(this.controlador.obtenerPreguntasDelForo(foro).toArray());
        for (Pregunta pre : this.controlador.obtenerPreguntasDelForo(foro)) {
            modelo.addElement(pre);
        }
        this.listPreguntas.setModel(modelo);
    }

    public void cargarListaDetalle() {
        DefaultListModel modelo = new DefaultListModel();
        List lista = this.controlador.obtenerInformacionPregunta(this.listPreguntas.getSelectedValue());
        try {
            modelo.add(0, "Usuario: " + lista.get(0));
            modelo.add(1, "Tipo de usuario: " + lista.get(1));
            modelo.add(2, "Titulo: " + lista.get(2));
            modelo.add(3, "Fecha de publicacion: " + lista.get(4));
            modelo.add(4, "Cantidad de respuestas : " + lista.get(5));
            modelo.add(5, "Fecha de la ultima respuesta : " + lista.get(6));
        } catch (Exception ex) {
        }
        this.listDetalle.setModel(modelo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddAnswer;
    private javax.swing.JButton buttonVerPregunta;
    private javax.swing.JButton buttonVerPregunta1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listDetalle;
    private javax.swing.JList<Pregunta> listPreguntas;
    private javax.swing.JLabel nameForo;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
