/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Controlador;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import modelo.Foro;
import modelo.Pregunta;
import modelo.Respuesta;
import modelo.Usuario;
import modelo.Voto;

/**
 *
 * @author Alexander
 */
public class ViewPregunta extends javax.swing.JFrame {

    private JFrame previo;
    private Controlador controlador;
    private Pregunta pregunta;
    private Foro foro;
    private Usuario usuario;
    private Respuesta respuesta1;

    public ViewPregunta(JFrame p, Pregunta pre, Foro fo, Controlador c, Usuario usuari) {
        this.previo = p;
        this.pregunta = pre;
        this.foro = fo;
        this.controlador = c;
        this.usuario = usuari;
        initComponents();
        this.namePregunta.setText(pre.getTitulo());
        this.nameForo.setText(fo.getTitulo());
        this.textAreaDetallePregunta.setText(pre.getDescripcion());
        this.textAreaDetallePregunta.setLineWrap(true);
        this.cargarListRespuesta();

        List<String> datosUsuario = this.controlador.obtenerDatosUsuario(this.usuario);
        switch (datosUsuario.get(4)) {
            case "Estudiante":
                this.jButton4.setVisible(false);
                break;
            case "Profesor":
                this.jButton4.setVisible(false);
                break;
            case "Registrador":
                this.jButton4.setVisible(false);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePregunta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listRespuestas = new javax.swing.JList<>();
        returnBtn = new javax.swing.JButton();
        nameForo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        labelPositivo = new javax.swing.JLabel();
        labelNegativo = new javax.swing.JLabel();
        positiveVote = new javax.swing.JLabel();
        negativeVote = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDetalles = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        buttonPositivos = new javax.swing.JButton();
        buttonNegativos = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaDetallePregunta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Respuestas - BitNet");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        namePregunta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namePregunta.setForeground(new java.awt.Color(153, 0, 153));
        namePregunta.setText("NamePregunta");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        listRespuestas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        listRespuestas.setForeground(new java.awt.Color(102, 0, 102));
        listRespuestas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listRespuestas.setSelectionBackground(new java.awt.Color(153, 153, 153));
        listRespuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listRespuestasMouseClicked(evt);
            }
        });
        listRespuestas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRespuestasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listRespuestas);

        returnBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnBtn.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        returnBtn.setForeground(new java.awt.Color(102, 0, 153));
        returnBtn.setText("");
        returnBtn.setToolTipText("Haz click para Volver");
        returnBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        nameForo.setText("NameForo");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 153));
        jButton2.setText("Publicar Respuesta");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        labelPositivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPositivo.setForeground(new java.awt.Color(0, 153, 0));
        labelPositivo.setText("Votos Positivos:");

        labelNegativo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNegativo.setForeground(new java.awt.Color(204, 0, 0));
        labelNegativo.setText("Votos Negativos:");

        listDetalles.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        listDetalles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDetallesValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listDetalles);

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        textArea.setPreferredSize(new java.awt.Dimension(866, 94));
        jScrollPane1.setViewportView(textArea);

        buttonPositivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/me gusta.jpg"))); // NOI18N
        buttonPositivos.setBorder(null);
        buttonPositivos.setBorderPainted(false);
        buttonPositivos.setContentAreaFilled(false);
        buttonPositivos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/me gusta2.jpg"))); // NOI18N
        buttonPositivos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/me gusta2.jpg"))); // NOI18N
        buttonPositivos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/me gusta2.jpg"))); // NOI18N
        buttonPositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPositivosActionPerformed(evt);
            }
        });

        buttonNegativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no me gusta.jpg"))); // NOI18N
        buttonNegativos.setBorder(null);
        buttonNegativos.setBorderPainted(false);
        buttonNegativos.setContentAreaFilled(false);
        buttonNegativos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no me gusta2.jpg"))); // NOI18N
        buttonNegativos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/me gusta2.jpg"))); // NOI18N
        buttonNegativos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no me gusta2.jpg"))); // NOI18N
        buttonNegativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNegativosActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("");
        jButton4.setToolTipText("Haz click para eliminar una Respuesta");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        textAreaDetallePregunta.setEditable(false);
        textAreaDetallePregunta.setColumns(20);
        textAreaDetallePregunta.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        textAreaDetallePregunta.setRows(5);
        jScrollPane4.setViewportView(textAreaDetallePregunta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(positiveVote)
                                .addGap(130, 130, 130)
                                .addComponent(negativeVote))
                            .addComponent(nameForo)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane3))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPositivo)
                                    .addComponent(buttonPositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonNegativos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNegativo)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namePregunta)
                        .addGap(0, 719, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameForo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namePregunta)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPositivo)
                                    .addComponent(labelNegativo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonPositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonNegativos))
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positiveVote)
                            .addComponent(negativeVote))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnBtnActionPerformed

    private void listRespuestasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRespuestasValueChanged
        this.respuesta1 = this.listRespuestas.getSelectedValue();
        this.cargarListaDetalle();
    }//GEN-LAST:event_listRespuestasValueChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.cargarListRespuesta();
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PublicarRespuesta principal = new PublicarRespuesta(this, this.pregunta, this.controlador, this.usuario);
        principal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonPositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPositivosActionPerformed
        if (this.listRespuestas.getSelectedIndex() != -1) {
            this.controlador.crearVoto(true, this.listRespuestas.getSelectedValue(), this.usuario);
            this.cargarListaDetalle();
        }

    }//GEN-LAST:event_buttonPositivosActionPerformed

    private void buttonNegativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNegativosActionPerformed
        if (this.listRespuestas.getSelectedIndex() != -1) {
            this.controlador.crearVoto(false, this.listRespuestas.getSelectedValue(), this.usuario);
            this.cargarListaDetalle();
        }
    }//GEN-LAST:event_buttonNegativosActionPerformed

    private void listRespuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRespuestasMouseClicked

    }//GEN-LAST:event_listRespuestasMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (this.listRespuestas.getSelectedIndex() != -1) {
            if (this.controlador.esUsuarioAdministrador(usuario)) {
                Boolean respuesta = false;

                VistaAvisoDialog aviso = new VistaAvisoDialog(this, true, respuesta, "Se eliminara todos las respuestas y asociaciones");
                aviso.setVisible(true);

                respuesta = aviso.obtenerRespuesta();
                if (respuesta) {

                    this.controlador.eliminarRespuesta(this.listRespuestas.getSelectedValue());
                    this.cargarListRespuesta();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna respuesta");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void listDetallesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDetallesValueChanged
        if (this.listDetalles.getSelectedIndex() == 1) {
            if (this.respuesta1 != null) {
                VerPerfil perfil = new VerPerfil(this, this.controlador.getPersistencia(), this.respuesta1.getUsuario(), 1);
                perfil.setVisible(true);
                perfil.setLocationRelativeTo(null);
                perfil.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();

            }

        }
    }//GEN-LAST:event_listDetallesValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
    private void cargarListaDetalle() {
        DefaultListModel modelo = new DefaultListModel();
        List respuestaInfo = this.controlador.obtenerInformacionRespuesta(this.listRespuestas.getSelectedValue());
        //se usa el triy catch porqu cuando se publica una nueva respuesta se activa el evento de valor cambiado en la lista respuesta y envia un objeto null y apareeen los errores de puntero.
        try {
            modelo.add(0, "Usuario: " + respuestaInfo.get(0));
            modelo.add(1, "Tipo de Usuario: " + respuestaInfo.get(1));
            modelo.add(2, "Fecha de publicacion: " + respuestaInfo.get(2));

            // modelo.add(2, "Respuesta: \n" + respuestaInfo.get(2));
            this.listDetalles.setModel(modelo);
            this.textArea.setText("Titulo: " + respuestaInfo.get(3) + '\n' + "Respuesta: \n" + respuestaInfo.get(4));

            this.textArea.setLineWrap(true);
            this.textArea.setEditable(false);
            this.labelPositivo.setText("Votos Positivos: " + (Integer) respuestaInfo.get(5));
            this.labelNegativo.setText("Votos Negativos: " + (Integer) respuestaInfo.get(6));
        } catch (Exception ex) {
        }
    }

    private void cargarListRespuesta() {
        DefaultListModel modelo = new DefaultListModel();

        //Arrays.sort(this.controlador.obtenerRepuestasDePregunta(pregunta).toArray());
        //ordenamos las respuestas por orden de la primera a la ultima respuesta, seria de la respuesta mas nueva primero a las mas vieja
        for (Respuesta respuesta : this.controlador.obtenerRepuestasDePregunta(pregunta)) {
            modelo.addElement(respuesta);
        }
        this.listRespuestas.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNegativos;
    private javax.swing.JButton buttonPositivos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelNegativo;
    private javax.swing.JLabel labelPositivo;
    private javax.swing.JList<String> listDetalles;
    private javax.swing.JList<Respuesta> listRespuestas;
    private javax.swing.JLabel nameForo;
    private javax.swing.JLabel namePregunta;
    private javax.swing.JLabel negativeVote;
    private javax.swing.JLabel positiveVote;
    private javax.swing.JButton returnBtn;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextArea textAreaDetallePregunta;
    // End of variables declaration//GEN-END:variables
}
