/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Admin
 */
@Entity
public class Foro implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Basic
    private String titulo;

    @OneToMany(targetEntity = Pregunta.class)
    private List<Pregunta> preguntas;

    public Foro() {
        preguntas = new ArrayList<>();
    }

    public Foro(String titulo) {
        this.titulo = titulo;
        preguntas = new ArrayList<>();
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public List<Pregunta> getPreguntas() {
        return this.preguntas;
    }

    public void setPreguntas(List<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }

    @Override
    public String toString() {
        return titulo;
    }

    public void agregarPregunta(Pregunta pregunta1) {
        this.preguntas.add(pregunta1);
    }
       public void quitarPregunta(Pregunta pregunta1) {
        this.preguntas.remove(pregunta1);
    }
}
