/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author Admin
 */
@Entity
public class Materia implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Basic
    private String materia;

    @Basic
    private String enlace;

    @ManyToMany(targetEntity = UsuarioAcademico.class, mappedBy = "materias")
    private Set<UsuarioAcademico> profesores;

    public Materia() {
        profesores = new HashSet();
    }

    public Materia(String materia, String link) {
        this.materia = materia;
        this.enlace = link;
        profesores = new HashSet();

    }

    public Long getId() {
        return this.id;
    }

    @Override
    public String toString() {
        return materia;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMateria() {
        return this.materia;
    }

    public void setMateria(String materia) {
        this.materia = materia;
    }

    public String getEnlace() {
        return this.enlace;
    }

    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }

    public Set<UsuarioAcademico> getProfesores() {
        return this.profesores;
    }

    public void setProfesores(Set<UsuarioAcademico> profesores) {
        this.profesores = profesores;
    }

}
