/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;

/**
 * @author Admin
 */
@Entity
public class Pregunta implements Serializable, Comparable<Pregunta> {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date fechaPublicacion;

    @Basic
    private String descripcion;

    @Basic
    private String titulo;

    @OneToMany(targetEntity = Respuesta.class)
    private List<Respuesta> respuestas;
    @ManyToOne
    private UsuarioAcademico usuario;
    @ManyToOne
    private Foro foro;

    public Pregunta() {
        respuestas = new ArrayList<>();
        this.fechaPublicacion = new Date();
    }

    public Pregunta(String titulo, String desc, UsuarioAcademico usuario, Foro foro) {
        this.foro = foro;
        this.titulo = titulo;
        this.descripcion = desc;
        respuestas = new ArrayList<>();
        this.usuario = usuario;
        this.fechaPublicacion = new Date();
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }

    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }

    public String getPregunta() {
        return this.descripcion;
    }

    public void setPregunta(String pregunta) {
        this.descripcion = pregunta;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public List<Respuesta> getRespuestas() {
        return this.respuestas;
    }

    public void setRespuestas(List<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }

    @Override
    public String toString() {
        return titulo;
    }

    public void agregarRespuesta(Respuesta respuesta) {
        this.respuestas.add(respuesta);
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public UsuarioAcademico obtenerPublicador() {

        return this.usuario;
    }

    public Date obtenerFechaDeUltimaRespuesta() {
        return this.respuestas.get(this.respuestas.size() - 1).getFechaPublicacion();
    }

    @Override
    public int compareTo(Pregunta o) {
        if (this.fechaPublicacion.getTime() < o.getFechaPublicacion().getTime()) {
            return -1;
        }
        if (this.fechaPublicacion.getTime() > o.getFechaPublicacion().getTime()) {
            return 1;
        }
        return 0;
    }

    public Foro getForo() {
        return foro;
    }

    public void setForo(Foro foro) {
        this.foro = foro;
    }

    public void quitarRespuesta(Respuesta respuesta) {
        this.respuestas.remove(respuesta);
    }

    public Foro eliminarForo() {
        Foro viejo = this.foro;
        this.foro = null;
        return viejo;
    }

    public void eliminarUsuario() {
        this.usuario.quitarPregunta(this);
        this.usuario = null;
    }

    public UsuarioAcademico getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuarioAcademico usuario) {
        this.usuario = usuario;
    }

}
