/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author Admin
 */
@Entity
public class Voto implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Basic
    private Boolean voto;
    @ManyToOne
    private UsuarioAcademico usuario;

    public Voto() {
    }

    public Voto(Boolean voto, UsuarioAcademico usu) {
        this.usuario = usu;
        this.voto = voto;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean isVoto() {
        return this.voto;
    }

    public void setVoto(Boolean voto) {
        this.voto = voto;
    }

    public UsuarioAcademico getUsuario() {
        return this.usuario;
    }



}
